
# KNOWING WORKS BUT BACKEND IS NOT RUNNING

# version: '3'
# services:
#   react-app:
#     image: whale80/pbtpublish
#     ports:
#       - "3000:3000"
#     networks:
#       - mern-stack-net
#     depends_on:
#       - api
#   api:
#    image: whale80/pbtbackend2.0
#    ports:
#      - 4444:4040
#    container_name: mern-api
#    networks:
#      - mern-stack-net
#    volumes:
#     - ./api/src:/usr/app/src
#    depends_on:
#     - mongo
#    mongo:
#     image: mongo:latest
#     ports:
#       - 27017:27017
#     networks:
#       - mern-stack
#     volumes:
#       - mongo-data:/data/db


# KNOWING WORKS BUT BACKEND IS NOT RUNNING

# Knowing works again

# version: '3'
# services:
#   react-app:
#     image: whale80/pbtpublish
#     ports:
#       - 3000:3000
#     networks:
#       - mern-stack-net
#     depends_on:
#       - api
#   api:
#     image: pbtserver
#     ports:
#       - 4444:4040
#     container_name: mern-api
#     networks:
#       - mern-stack-net
#     volumes:
#       - api-src:/usr/app/src
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo:latest
#     ports:
#       - 27017:27017
#     networks:
#       - mern-stack-net
#     volumes:
#       - mongo-data:/data/db
      
# networks:
#   mern-stack-net:
#     driver: bridge

# volumes:
#   api-src:
#     driver: local
#   mongo-data:
#     driver: local

# knowing works again

# version: '3'
# services:
#   react-app:
#     image: updatedfrontend
#     ports:
#       - 3000:3000
#     networks:
#       - mern-stack-net
#     depends_on:
#       - api
#   api:
#     image: newpbtserver:latest
#     ports:
#       - 4444:4040
#     container_name: mern-api
#     networks:
#       - mern-stack-net
#     volumes:
#       - api-src:/usr/app/src
#     environment:
#       - MONGO_URL=mongodb+srv://PBT:rhQhpPMAB3ZQTqi@cluster0.ahmbuv5.mongodb.net/test?retryWrites=true&w=majority
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo:latest
#     networks:
#       - mern-stack-net
#     container_name: mern-mongo
#     command: "mongod --bind_ip_all"
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=PBT
#       - MONGO_INITDB_ROOT_PASSWORD=rhQhpPMAB3ZQTqi
#       - MONGO_INITDB_DATABASE=test
# networks:
#   mern-stack-net:
#     driver: bridge
# volumes:
#   api-src:
#     driver: local
#   mongo-data:
#     driver: local

# version: '3'
# services:
#   react-app:
#     image: updatedfrontend2.0
#     ports:
#       - 3000:3000
#     networks:
#       - mern-stack-net
#     depends_on:
#       - api
#   api:
#     image: newpbtserver:latest
#     ports:
#       - 4444:4040
#     container_name: mern-api
#     networks:
#       - mern-stack-net
#     volumes:
#       - api-src:/usr/app/src
#     environment:
#       - MONGO_URL=mongodb+srv://PBT:rhQhpPMAB3ZQTqi@cluster0.ahmbuv5.mongodb.net/tryingagain?retryWrites=true&w=majority
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo:latest
#     networks:
#       - mern-stack-net
#     container_name: mern-mongo
#     command: "mongod --bind_ip_all"
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=PBT
#       - MONGO_INITDB_ROOT_PASSWORD=rhQhpPMAB3ZQTqi
#       - MONGO_INITDB_DATABASE=tryingagain
#     ports:
#       - 27017:27017
# networks:
#   mern-stack-net:
#     driver: bridge
# volumes:
#   api-src:
#     driver: local
# version: '3'
# services:
#   react-app:
#     image: finaltest
#     ports:
#       - 3000:3000
#     networks:
#       - mern-stack-net
#     depends_on:
#       - api
#   api:
#     image: apibackend
#     ports:
#       - 4444:4040
#     container_name: mern-api
#     networks:
#       - mern-stack-net
#     volumes:
#       - api-src:/Backend
#     environment:
#       - MONGO_URL=mongodb+srv://PBT:rhQhpPMAB3ZQTqi@cluster0.ahmbuv5.mongodb.net/tryingagain?retryWrites=true&w=majority
#     depends_on:
#       - mongodb
#   mongodb:
#     image: mongo:latest
#     networks:
#       - mern-stack-net
#     container_name: mern-mongo-app
#     command: "mongod --bind_ip_all"
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=PBT
#       - MONGO_INITDB_ROOT_PASSWORD=rhQhpPMAB3ZQTqi
#       - MONGO_INITDB_DATABASE=tryingagain
#     ports:
#       - 27017:27017
#   nginx:
#     image: nginx:1.19.0
#     ports:
#       - 80:80
#     volumes:
#       - ./nginx.conf:/etc/default.conf
#     depends_on:
#       - api
# networks:
#   mern-stack-net:
#     driver: bridge
#   volumes:
#   api-src:
#     driver: local
# volumes:
#   nginx:
#     driver: local

#   volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf

version: '3'
services:
  react-app:
    image: finaltest
    ports:
      - 3000:3000
    networks:
      - mern-stack-net
    depends_on:
      - api
  api:
    image: apibackend
    ports:
      - 4444:4040
    container_name: mern-api
    networks:
      - mern-stack-net
    volumes:
      - api-src:/Backend
    environment:
      - MONGO_URL=mongodb+srv://PBT:rhQhpPMAB3ZQTqi@cluster0.ahmbuv5.mongodb.net/tryingagain?retryWrites=true&w=majority
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    networks:
      - mern-stack-net
    container_name: mern-mongo-app
    command: "mongod --bind_ip_all"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=PBT
      - MONGO_INITDB_ROOT_PASSWORD=rhQhpPMAB3ZQTqi
      - MONGO_INITDB_DATABASE=tryingagain
    ports:
      - 27017:27017
  nginx:
    image: nginx:1.19.0
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
networks:
  mern-stack-net:
    driver: bridge
volumes:
  api-src:
    driver: local
